[[constraint]]
  name = "github.com/joho/godotenv"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.4.0"

[[constraint]]
  name = "golang.org/x/text"
  version = "^0.3.0"